/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;
import java.awt.event.ActionEvent;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author pc
 */
public class EditTeacher extends javax.swing.JFrame {

    /**
     * Creates new form EditTeacher
     */
    public EditTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_editlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teacher_name = new javax.swing.JTextField();
        teacher_age = new javax.swing.JTextField();
        teacher_salary = new javax.swing.JTextField();
        teacher_graddeg = new javax.swing.JTextField();
        teacher_gradyr = new javax.swing.JTextField();
        teacher_exp = new javax.swing.JTextField();
        teacher_sub = new javax.swing.JTextField();
        EditButton1 = new javax.swing.JButton();
        DeleteButton1 = new javax.swing.JButton();
        BackButtonedit_t = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t_editlabel.setFont(new java.awt.Font("Californian FB", 3, 24)); // NOI18N
        t_editlabel.setText("Edit/Delete Teacher");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Age:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Salary:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Graduation Degree:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Graduation Year:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Years Of experience:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Subject:");

        teacher_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        teacher_age.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        teacher_salary.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        teacher_graddeg.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        teacher_gradyr.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        teacher_exp.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        teacher_sub.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        EditButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        EditButton1.setForeground(new java.awt.Color(0, 51, 255));
        EditButton1.setText("Edit");
        EditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton1ActionPerformed(evt);
            }
        });

        DeleteButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        DeleteButton1.setForeground(new java.awt.Color(255, 0, 0));
        DeleteButton1.setText("Delete");
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });

        BackButtonedit_t.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        BackButtonedit_t.setText("Back");
        BackButtonedit_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonedit_tActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(t_editlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacher_name, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacher_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(teacher_salary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teacher_gradyr, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(teacher_graddeg)
                            .addComponent(teacher_exp)
                            .addComponent(teacher_sub))))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackButtonedit_t, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(t_editlabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(teacher_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teacher_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(teacher_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_graddeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_gradyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19)
                .addComponent(BackButtonedit_t)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(EditButton1)
                .addGap(34, 34, 34)
                .addComponent(DeleteButton1)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonedit_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonedit_tActionPerformed
        // TODO add your handling code here:
        Home_Page pg=new Home_Page();
        pg.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonedit_tActionPerformed

    private void EditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton1ActionPerformed
        // TODO add your handling code here:
        String t_name=teacher_name.getText();
        String t_age=teacher_age.getText();
        String t_salary=teacher_salary.getText();
        String t_degree=teacher_graddeg.getText();
        String t_year=teacher_gradyr.getText();
        String t_exp=teacher_exp.getText();
        String t_sub=teacher_sub.getText();
        if(t_name.equals("")||t_age.equals("")||t_salary.equals("")||t_degree.equals("")||t_year.equals("")||t_exp.equals("")||t_sub.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please fill all data required.");
            
            
        }
        else{
        
            Teacher teacher1=new Teacher(t_name,t_age,t_salary,t_degree,t_year,t_exp,t_sub);
            AddTeachers at=new  AddTeachers();
            at.T_SubmitButton(evt);
            SchoolManagementSystem s=new SchoolManagementSystem();
            List<Teacher> l1=s.getArraylist();
           
                
            for(int i=0;i<l1.size();i++){
                Teacher tch=l1.get(i);
                if(t_name.equals(tch.name)&&t_age.equals(tch.age)&&t_degree.equals(tch.grad_degree)){
                    tch.updateSalary(t_salary);
                    l1.get(i).salary=t_salary; 
                    JOptionPane.showMessageDialog(rootPane, "data has been recorded.");
                    break;
                
            } else {
                    continue;
                    
                    
                }
                  
            }
           
            
    
            
            //List<Teacher> list1=new ArrayList<>();
            
           
       
    }//GEN-LAST:event_EditButton1ActionPerformed
    }
    public void EditBtn(java.awt.event.ActionEvent evt){
        EditButton1ActionPerformed(evt);
    }
    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        // TODO add your handling code here:
        String t_name=teacher_name.getText();
        String t_age=teacher_age.getText();
        String t_salary=teacher_salary.getText();
        String t_degree=teacher_graddeg.getText();
        String t_year=teacher_gradyr.getText();
        String t_exp=teacher_exp.getText();
        String t_sub=teacher_sub.getText();
        if(t_name.equals("")||t_age.equals("")||t_salary.equals("")||t_degree.equals("")||t_year.equals("")||t_exp.equals("")||t_sub.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please fill all data required.");
            
            
        }
        else{
        
            Teacher teacher1=new Teacher(t_name,t_age,t_salary,t_degree,t_year,t_exp,t_sub);
            AddTeachers at=new  AddTeachers();
            at.T_SubmitButton(evt);
            SchoolManagementSystem s=new SchoolManagementSystem();
            List<Teacher> l1=s.getArraylist();
           
                
            for(int i=0;i<l1.size();i++){
                Teacher tch=l1.get(i);
                if(t_name.equals(tch.name)&&t_age.equals(tch.age)&&t_degree.equals(tch.grad_degree)){
                    l1.remove(i);
                    JOptionPane.showMessageDialog(rootPane, "data has been deleted.");
                    break;
                
            } else {
                    continue;
                    
                    
                }
                  
            }
           
            
    
            
            //List<Teacher> list1=new ArrayList<>();
            
           
        
    }   
    }//GEN-LAST:event_DeleteButton1ActionPerformed
    public void DeleteBtn(java.awt.event.ActionEvent evt){
        DeleteButton1ActionPerformed(evt);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButtonedit_t;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton EditButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel t_editlabel;
    private javax.swing.JTextField teacher_age;
    private javax.swing.JTextField teacher_exp;
    private javax.swing.JTextField teacher_graddeg;
    private javax.swing.JTextField teacher_gradyr;
    private javax.swing.JTextField teacher_name;
    private javax.swing.JTextField teacher_salary;
    private javax.swing.JTextField teacher_sub;
    // End of variables declaration//GEN-END:variables

  
}
